import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { expect, test } from "@playwright/test";
import { medicationSparseOpening, medicationSparseUpdate, medicationTwoOpening, medicationNeverRestarted, medicationRestartedAgain } from "../fixtures/medication-model";
import { acceptOpeningGroups, directAnswers, goTo, savePdf, storedState } from "./draft4-helpers";

test("Draft 4 retains drafts and proposals across screens, revisits reporter details, and displays the real current or earlier PDF", async ({ page }, info) => {
  let pdfRequests = 0;
  page.on("request", (r) => { if (r.url().endsWith("/api/case/pdf")) pdfRequests++; });
  await page.goto("/");
  await page.getByLabel("Case description", { exact: true }).fill(medicationSparseOpening);
  await page.screenshot({ path: info.outputPath("describe-desktop.png"), fullPage: true });
  await page.getByRole("button", { name: "Review Wilson’s understanding", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Review the case details" })).toBeVisible();
  const beforeReview = await storedState(page);
  const age = page.locator("#case-card-patient dl > div").filter({ has: page.getByText("Age", { exact: true }) });
  await age.getByRole("button", { name: "Change", exact: true }).click();
  await age.getByLabel("New Age", { exact: true }).fill("41");
  await goTo(page, "Describe");
  await expect(page.getByText(medicationSparseOpening, { exact: true })).toBeVisible();
  await goTo(page, "Review details");
  await expect(age.getByLabel("New Age", { exact: true })).toHaveValue("41");
  expect(await storedState(page)).toEqual(beforeReview);
  await age.getByRole("button", { name: "Keep draft" }).click();
  await acceptOpeningGroups(page);
  expect((await storedState(page)).case.patient.facts.ageYears.resolvedValue?.value).toEqual({ kind: "known", value: 41 });
  await goTo(page, "Review details");
  await expect(page.getByRole("button", { name: "Show more fields" }).first()).toBeVisible();
  await expect(page.locator('[id^="case-card-"]').getByText("Not provided", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("region", { name: "Information still needed", exact: true })).toContainText("Treatment history for amoxicillin");
  await expect(page.locator("#clinical-question")).toContainText("Answer only what you know; these observations do not establish causality.");
  await page.getByLabel("Clinical update", { exact: true }).fill(medicationSparseUpdate);
  await directAnswers(page);
  await page.getByLabel("Was this medication stopped?", { exact: true }).selectOption("true");
  await page.getByLabel("When was it stopped?", { exact: true }).selectOption("known");
  await page.getByLabel("Stop date", { exact: true }).fill("2026-09-18");
  await page.getByLabel("Was this medication stopped?", { exact: true }).selectOption("false");
  await page.getByLabel("Was this medication stopped?", { exact: true }).selectOption("true");
  await expect(page.getByLabel("When was it stopped?", { exact: true })).toHaveValue("");
  await page.getByLabel("When was it stopped?", { exact: true }).selectOption("known");
  await page.getByLabel("Stop date", { exact: true }).fill("2026-09-18");
  await goTo(page, "Reporter details");
  await page.getByLabel("Reporter first name", { exact: true }).fill("Casey");
  await page.getByLabel("Reporter last name", { exact: true }).fill("Reed");
  await page.getByLabel("Reporter email", { exact: true }).fill("casey@example.test");
  await expect(page.getByRole("button", { name: "Add reporter details", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Answer clinical questions", exact: true })).toBeVisible();
  const duringDraft = await storedState(page);
  await goTo(page, "Review & save");
  await expect(page.getByText("You have unsaved reporter details.", { exact: false })).toBeVisible();
  await expect(page.getByText("You have an unsent clinical draft", { exact: false })).toBeVisible();
  await expect(page.getByRole("button", { name: "Generate PDF", exact: true })).toBeDisabled();
  expect(pdfRequests).toBe(0);
  await goTo(page, "Review details");
  expect(await storedState(page)).toEqual(duringDraft);
  await expect(page.getByLabel("Clinical update", { exact: true })).toHaveValue(medicationSparseUpdate);
  await expect(page.getByLabel("Stop date", { exact: true })).toHaveValue("2026-09-18");
  await page.getByRole("button", { name: "Prepare changes for review", exact: true }).click();
  await expect(page.getByRole("button", { name: "Accept these changes", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Review the proposed update", exact: true })).toBeFocused();
  await expect(page.getByRole("heading", { name: "Review the proposed update", exact: true })).toBeInViewport();
  await expect(page.locator("article").filter({ has: page.getByRole("button", { name: "Accept these changes", exact: true }) }).first().getByRole("heading").first()).toBeInViewport();
  await page.screenshot({ path: info.outputPath("update-focused.png") });
  const pending = await storedState(page);
  await expect(page.getByRole("article", { name: /amoxicillin — Treatment history/ })).toBeVisible();
  await expect(page.getByRole("region", { name: "Answer, add or correct information", exact: true })).toContainText("Review the proposed changes before sending another update.");
  await page.getByText("Draft another update", { exact: true }).click();
  await expect(page.getByRole("button", { name: "Prepare changes for review", exact: true })).toBeDisabled();
  await goTo(page, "Reporter details");
  await expect(page.getByLabel("Reporter email", { exact: true })).toHaveValue("casey@example.test");
  await goTo(page, "Review & save");
  expect(pdfRequests).toBe(0);
  await goTo(page, "Review details");
  expect(await storedState(page)).toEqual(pending);
  await page.getByRole("button", { name: "Accept these changes", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Case summary", exact: true })).toBeFocused();
  await expect(page.getByRole("region", { name: "Information still needed", exact: true })).toBeHidden();
  await expect(page.getByRole("heading", { name: "Answer, add or correct information", exact: true })).toBeVisible();
  await goTo(page, "Reporter details");
  await expect(page.getByLabel("Reporter email", { exact: true })).toHaveValue("casey@example.test");
  await page.getByLabel("Date of this report", { exact: true }).fill("2026-09-22");
  await page.getByLabel("Do not disclose my identity to the manufacturer", { exact: true }).check();
  await page.screenshot({ path: info.outputPath("reporter-desktop.png"), fullPage: true });
  await page.getByRole("button", { name: "Add reporter details", exact: true }).click();
  await expect(page.getByRole("link", { name: "Save PDF", exact: true })).toBeVisible();
  const originalUrl = await page.getByTitle("Generated Form FDA 3500", { exact: true }).getAttribute("src");
  expect(originalUrl).toMatch(/^blob:/);
  expect(pdfRequests).toBe(1);
  const completed = await storedState(page);
  await page.getByText("Report coverage and omitted information", { exact: true }).click();
  const coverage = page.locator("details").filter({ has: page.getByText("Report coverage and omitted information", { exact: true }) });
  await expect(coverage).toContainText("Relevant history: explicitly reported as absent");
  await expect(coverage).toContainText("Address: not supplied");
  await expect(coverage).not.toContainText("not present");
  await expect(coverage.getByRole("heading", { name: "Fields this preview does not support" })).toBeVisible();
  await page.screenshot({ path: info.outputPath("pdf-desktop.png"), fullPage: true });
  await goTo(page, "Reporter details");
  await expect(page.getByLabel("Reporter email", { exact: true })).toHaveValue("casey@example.test");
  await page.getByRole("button", { name: "Save reporter details", exact: true }).click();
  await expect(page.getByTitle("Generated Form FDA 3500", { exact: true })).toHaveAttribute("src", originalUrl!);
  expect((await storedState(page)).case.revision).toBe(completed.case.revision);
  expect(pdfRequests).toBe(1);
  await goTo(page, "Review details");
  await page.getByLabel("Clinical update", { exact: true }).fill("Unsent additional observation.");
  await goTo(page, "Review & save");
  await expect(page.getByTitle("Generated Form FDA 3500", { exact: true })).toHaveAttribute("src", originalUrl!);
  await expect(page.getByText("You have an unsent clinical draft", { exact: false })).toBeVisible();
  expect(pdfRequests).toBe(1);
  await goTo(page, "Reporter details");
  await page.getByLabel("Reporter email", { exact: true }).fill("corrected@example.test");
  await page.getByRole("button", { name: "Save reporter details", exact: true }).click();
  await expect(page.getByRole("link", { name: "Save PDF", exact: true })).toBeVisible();
  expect(pdfRequests).toBe(2);
  expect(await page.getByTitle("Generated Form FDA 3500", { exact: true }).getAttribute("src")).not.toBe(originalUrl);
  const pdf = await savePdf(page);
  const path = info.outputPath("reporter-corrected.pdf");
  await pdf.saveAs(path);
  const { stdout } = await promisify(execFile)(process.env.PYPDF_PYTHON ?? "python3", ["tools/pdf/independent_readback.py", path, "--named"]);
  const fields = JSON.parse(stdout).namedFields;
  expect(fields["topmostSubform[0].Page7[0].SecG_Reporter[0].Email[0]"]).toBe("corrected@example.test");
  expect(fields["topmostSubform[0].Page7[0].SecG_Reporter[0].IdentityNo[0]"]).toBe("/1");
  expect(fields["topmostSubform[0].Page1[0].SecA_Patient[0].AgeValue[0]"]).toBe("41");
  for (const [width, height] of [[390, 844], [1280, 800]]) {
    await page.setViewportSize({ width, height });
    for (const screen of ["Describe", "Review details", "Reporter details", "Review & save"] as const) {
      await goTo(page, screen);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
      await page.screenshot({ path: info.outputPath(`${screen.replaceAll(/\W+/g, "-")}-${width}.png`), fullPage: true });
    }
  }
});

test("a retained PDF is labelled earlier during pending clinical correction and obsolete medication drafts cannot return", async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await page.getByLabel("Case description", { exact: true }).fill(medicationTwoOpening);
  await page.getByRole("button", { name: "Review Wilson’s understanding", exact: true }).click();
  await acceptOpeningGroups(page);
  await goTo(page, "Reporter details");
  await page.getByRole("button", { name: "Prefer not to provide reporter details" }).click();
  await expect(page.getByRole("link", { name: "Save PDF", exact: true })).toBeVisible();
  const url = await page.getByTitle("Generated Form FDA 3500", { exact: true }).getAttribute("src");
  await goTo(page, "Review details");
  const product = page.locator("#case-card-product-1");
  const recurrence = product.locator("dl > div").filter({ has: page.getByText("Event returned after restarting", { exact: true }) });
  // Draft a direct correction but submit a prerequisite correction conversationally.
  await recurrence.getByRole("button", { name: "Change", exact: true }).click();
  await recurrence.getByLabel("New Event returned after restarting", { exact: true }).selectOption("false");
  await page.getByLabel("Clinical update", { exact: true }).fill(medicationNeverRestarted);
  await page.getByRole("button", { name: "Prepare changes for review", exact: true }).click();
  await expect(page.getByRole("button", { name: "Accept these changes", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Review the proposed update", exact: true })).toBeFocused();
  await expect(page.getByRole("heading", { name: "Review the proposed update", exact: true })).toBeInViewport();
  await expect(page.locator("article").filter({ has: page.getByRole("button", { name: "Accept these changes", exact: true }) }).first().getByRole("heading").first()).toBeInViewport();
  await page.screenshot({ path: info.outputPath("update-focused.png") });
  await goTo(page, "Review & save");
  await expect(page.getByTitle("Earlier generated Form FDA 3500", { exact: true })).toHaveAttribute("src", url!);
  await expect(page.getByText("Earlier PDF —", { exact: false })).toBeVisible();
  await expect(page.getByRole("link", { name: "Save PDF", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Generate updated PDF", exact: true })).toBeDisabled();
  await goTo(page, "Review details");
  await page.getByRole("button", { name: "Accept these changes", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Case summary", exact: true })).toBeFocused();
  await expect(recurrence.getByLabel("New Event returned after restarting", { exact: true })).toHaveCount(0);
  await page.getByLabel("Clinical update", { exact: true }).fill(medicationRestartedAgain);
  await page.getByRole("button", { name: "Prepare changes for review", exact: true }).click();
  await page.getByRole("button", { name: "Accept these changes", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Information still needed", exact: true })).toBeFocused();
  await directAnswers(page);
  await expect(page.getByLabel("Did the event return after restarting it?", { exact: true })).toHaveValue("");
  expect((await storedState(page)).case.products[0].facts.recurred.resolvedValue).toBeUndefined();
});
